networks:
  common-net:
    name: common-net
    driver: bridge

services:
  nginx:
    image: nginx:1.31.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - "ragNode"
    links:
      - "ragNode:RagWeb"
    networks:
      - common-net

  ragNode:
    build:
      context: ./test_1
      dockerfile: Dockerfile
    image: rag-node:24.19.0
    container_name: ragNode
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - "mariadb:mariadb"
    expose:
      - "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Seoul
      OLLAMA_HOST: http://host.docker.internal:11434
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    networks:
      - common-net

  mariadb:
    image: mariadb:12.3.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    #expose:
    #  - "3306"
    ports:
      - "3306:3306"
    networks:
      - common-net

volumes:
  mariadb-data:
